version: 2
jobs:
  lint:
    docker:
      - image: python:3.7
    working_directory: ~/sanic-healthchecks
    steps:
      - checkout
      - run: pip install poetry==0.12.11
      - run: poetry install
      - run: poetry run python -m black --check .
      - run: poetry run python -m pylint examples sanic_healthchecks

  publish:
    docker:
      - image: python:3.7
    working_directory: ~/sanic-healthchecks
    steps:
      - checkout
      - run: pip install poetry==0.12.11
      - run: poetry install --no-dev
      - run:
          name: Publish package
          command: |
            poetry publish --username=$PYPI_USERNAME --password $PYPI_PASSWORD --build --no-interaction -vv

workflows:
  version: 2
  build:
    jobs:
      - lint
      - publish:
          requires:
            - lint
          filters:
            branches:
              only: master
            tags:
              only: /^\d+\.\d+\.\d+$/
