on: pull_reques
name: PR builder for sanic-healthchecks
jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@master
      with:
        args: install
    - name: Run black
      uses: abatilo/actions-poetry@master
      with:
        args: run python -m black --check .
  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@master
      with:
        args: install
    - name: Run pylint
      uses: abatilo/actions-poetry@master
      with:
        args: run python -m pylint examples sanic_healthchecks
