on:
  push:
    branches:
      - master
name: Publish sanic-healthchecks
jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@master
      with:
        args: install
    - name: Run black
      uses: abatilo/actions-poetry@master
      with:
        args: run python -m black --check .
  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@master
      with:
        args: install
    - name: Run pylint
      uses: abatilo/actions-poetry@master
      with:
        args: run python -m pylint examples sanic_healthchecks
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [black, pylint]
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@master
      with:
        args: install
    - name: publish
      uses: abatilo/actions-poetry@master
      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      with:
        args: publish --build --no-interaction -vv --username $PYPI_USERNAME --password
          $PYPI_PASSWORD
